import turtle
win = turtle.Screen()

a = 100
b = a/2-50

tommy = turtle.Turtle()
tommy.goto(-50, 0)
tommy.shape("turtle")
tommy.color("#009900")
tommy.begin_fill()
tommy.forward(a)
tommy.left(90)
tommy.forward(a)
tommy.left(90)
tommy.forward(a)
tommy.left(90)
tommy.forward(a)
tommy.left(90)
tommy.end_fill()
tommy.penup()
tommy.goto(b, -25)
tommy.left(90)
tommy.color("black")

tyler = turtle.Turtle()
tyler.penup()
tyler.goto(-50, -150)
tyler.shape("turtle")
tyler.pendown()
tyler.color("purple")
tyler.begin_fill()
tyler.forward(a)
tyler.left(90)
tyler.forward(a)
tyler.left(90)
tyler.forward(a)
tyler.left(90)
tyler.forward(a)
tyler.left(90)
tyler.end_fill()
tyler.penup()
tyler.goto(b, -175)
tyler.left(90)
tyler.color("black")
win.exitonclick()